### ISSUE TITLE
TSA im Eigenbau

### ISSUE THREAD

**Issue by landrix** [elbosso/elbosso.github.io#13]
Hi, ich hab Deinen Artikel über eine eigene TSA und dieses Repo hier gefunden

https://elbosso.github.io/tsa_openssl_eigenbau.html

 https://github.com/elbosso/rfc3161timestampingserver

Ist das ganze noch aktiv? Hattest Du Erfolg in Summe? Könnte man sich mit Dir dazu austauschen?

VG, Sven

**Comment by elbosso** [comment]
Hallo, ja - tatsächlich ist das Projekt noch sehr lebendig: nicht nur benutze ich es ständig (zum Beispiel fürs Code Signing) sondern entwickle es auch immer mal wieder weiter. Die letzte Release stammt von Mitte dieses Jahres (https://elbosso.github.io/timestamping_server___release_version_1_6_0.html#content). Das letzte größere funktionale Update liegt ein wenig weiter zurück und beschäftigte sich mit der Erstellung von Timestamps die zur gerichtsfesten Langzeitarchivierung eingesetzt werden können (https://elbosso.github.io/timestamping_server___release_version_1_3_0.html).

Für die weiteren funktionalen Features habe ich eine Diskussion eingerichtet (https://elbosso.github.io/timestamping_server___release_version_1_3_0.html) - die ist allerdings im Moment eher noch ein Monolog.

Also um auf die Fragen zu antworten:
* Ist noch aktiv
* Funktioniert hervorragend
* Klar kann man sich austauschen!

**Comment by landrix** [comment]
Sehr schön, gerade das Thema "Timestamps für gerichtsfesten Langzeitarchivierung" ist mein Thema. Ich weigere mich einfach für einen Timestamp  0,01 EUR für irgend eine TSA hinzublättern. Am Ende ist das mit Kanonen auf Spatzen geschossen, dass kann ich keinem Kunden vermitteln. Ich werde mich mal in Dein Projekt reinarbeiten, es ist derzeit das einzige mir derartig bekannte.
