### ISSUE TITLE
Feedback zu Einbinden von Wettervorhersagedaten in Grafana

### ISSUE THREAD

**Issue by guthubps1304** [elbosso/elbosso.github.io#5]
habe dein python ausprobiert auf ubuntu - bekommen folgenden fehler:

Traceback (most recent call last):
  File "/home/influx/./wetter.py", line 2, in <module>
    from influxdb import InfluxDBClient
ModuleNotFoundError: No module named 'influxdb'

**Comment by elbosso** [comment]
Hallo,

tut mir leid, dass es so lange gedauert hat.
Das Problem kann durch verschiedenes ausgelöst werden: Zunächst mal muss das Modul installiert sein. Das kann entweder durch 
```
pip install influxdb
```
oder (Python 3)
```
pip3 install influxdb
```
geschehen.
Wenn danach immer noch die Ausschrift kommt, kann es sein, dass das Modul für eine andere Version Python installiert wurde als die, die für die Ausführung benutzt wird.

Hast Du das Skript einfach so ausgeführt oder explizit einen Python-Interpreter gewählt - also beispielsweise
```
python3 /home/pi/weatherforecast.py
```
Das Skript selbst geht von Python 3 aus (siehe erste Zeile) - so dass eine mögliche Ursache des Fehlers wäre, dass Du das benötigte Modul mit `pip` statt `pip3` installiert hast  und es Python deshalb nicht finden kann...

Ich habe das Skript in einer aktualisierten Version angehängt, da die API seit dem ich den Artikel geschrieben habe den Zugriff per Pythons `request` Modul nicht mehr erlaubt - aus diesem Grund gibt sich die neue Version jetzt als Firefox aus - damit funktionierts dann auch wieder.

Die zwei auskommentierten `print`-Anweisungen kann man testweise aktivieren um zu sehen, dass alles korrekt funktioniert.

Außerdem habe ich noch ein paar Kommentare ergänzt. 
All das gibts demnächst auch als Aktualisierung des Artikels - wenn die raus ist werde ich das Ticket hier auch schließen - vorausgesetzt, Du meldest bis dahin nicht noch andere Probleme!

```python
#!/usr/bin/env python3
from influxdb import InfluxDBClient
import requests
import json
import datetime
import socket

#host of the influxdb used to store the data
influxhost=''
#port of the influxdb used to store the data
influxport=
#username for accessing the influxdb used to store the data
influxusername''
#password for accessing the influxdb used to store the data
influxpassword=''
#name of the influxdb database used to store the data
monitoringdbname=''
#user agent (python requests standard user agent is blocked by the api
useragent='Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20100101 Firefox/10.0'
#latitude of the location the forecast is wanted for (german: Breitengrad)
latitude=
#longitude of the location the forecast is wanted for (german: Längengrad)
longitude=
#API url
url='https://api.met.no/weatherapi/locationforecast/2.0/.json?lat={latitude}&lon={longitude}'.format(latitude=latitude,longitude=longitude)
#name of the location the forecast is wanted for (german: Längengrad)
locality=""
#value for the host tag when writing to the influxdb
monitoringhost=socket.getfqdn()
#if you want the ip address rather than the hosts name, do
#monitoringhost=socket.gethostbyname(socket.getfqdn())

client = InfluxDBClient(host=influxhost, port=influxport)
#if influx requires authentication, use the following line instead of the one above:
#client = InfluxDBClient(host=influxhost, port=influxport,username=influxusername, password=influxpasword)

databases = client.get_list_database()


databaseAlreadyThere =False


for item in databases:
    if item['name'] == monitoringdbname:
        databaseAlreadyThere = True


if databaseAlreadyThere == False:
    client.create_database(monitoringdbname)


client.switch_database(monitoringdbname)


headers = {
    'User-Agent': useragent
}

#print(url)
response = requests.get(url, headers=headers)
#print(response.content)
data = json.loads(response.content.decode('utf-8'))
timeseries=data['properties']['timeseries']
lon=data['geometry']['coordinates'][0]
lat=data['geometry']['coordinates'][1]
height=str(float(data['geometry']['coordinates'][2])*0.3048)
json_bodies=[]
for timeserie in timeseries:
    stats = {}
    data=timeserie['data']['instant']['details']
    for x in data:
        if isinstance(data[x],dict)==False:
            stats[x] = data[x]
    if 'next_1_hours' in timeserie['data'].keys():
        stats['precipitation_amount']=timeserie['data']['next_1_hours']['details']['precipitation_amount']
    json_body = []
    jb={}
    jb["measurement"]="WeatherForecast"
    tags={}
    tags["Server"]=monitoringhost
    tags["Longitude"]=lon
    tags["Latitude"]=lat
    tags["Height"]=height
    tags["Location"]=locality
    jb["tags"]=tags
    jb["time"]=timeserie['time']
    jb["fields"]=stats
    json_body.append(jb)
    client.write_points(json_body)
```

**Comment by guthubps1304** [comment]
Kein Problem und danke für die Info. 
Ich habe den ersten Schritt nicht gemacht,  da auf meinem Ubuntu die influxdb schon installierte ist und läuft. Probiere das mal als erstes. 

Frage: was genau macht der Befehl pip3 install influxdb?

Gruß Peter 

⁣BlueMail for Android herunterladen ​

**Comment by elbosso** [comment]
Ahh, ja: das ist wie in anderen Programmiersprachen (früher, in Zeiten von C und C++ häte so etwas Bibliothek oder Library geheißen) es gibt diverse Projekte, die oft benutzte oder benötigte Funktionalitäten sammeln und sie anderen zur Verfügung stellen, so dass man nicht mehr alles vom Urschleim aus selber programmieren muss. Bei Python heißt so was eben Modul. Also eine Sammlung von fertigen Funktionen, die man einfach in eigenen Programmen nutzen kann. In diesem Fall sind das eben Funktionen, die das Netzwerkprotokoll des InfluxDB Servers implementieren, so dass man einfach sagen kann "Schicke diese daten an Influx" und die Funktionen aus dem Modul übernehmen das (und das anschließende Fehlerhandling)...

**Comment by elbosso** [comment]
und `pip` oder `pip3` sind die Paketmanager für Python - also das was `apt` (oder `apt-get`) für Ubuntu sind. Man könnte für Ubuntu diese Pakete auch anders installieren - es gibt dafür fertige `.deb`-Pakete, die man entsprechend mit `apt` benutzen könnte - allerdings fallen mir die Namen dafür gerade nicht ein und die Benutzung von `pip` hat auch noch andere Vorteile (außerdem habe ich den Verdacht, dass das entsprechende `.deb` nichts anderes tut als `pip` aufzurufen...)
