### ISSUE TITLE
Feedback zu Lyapunov-Koeffizienten

### ISSUE THREAD

**Issue by Coarl93** [elbosso/elbosso.github.io#6]
[Lyapunov-Koeffizienten](https://elbosso.github.io/lyapunov_koeffizienten)

Hallo Elbosso, 

die Diagramme zur Bifurkation und zu den Lyapunov-Koeffizienten sieht super aus.
Ich arbeite zur Zeit für meine Bachelorarbeit daran.
Können sie mir Literatur zur Erzeugung des Bifurkationsdiagramm und zu Lyapunov empfehlen?

Danke und Viele Grüße

**Comment by elbosso** [comment]
Hallo,

dafür würde ich zunächst erst einmal Steven Strogatz "nonlinear dynamics and chaos" - z.B. bei Amazon https://www.amazon.de/Nonlinear-Dynamics-Chaos-Applications-Nonlinearity/dp/0813349109/ref=sr_1_1?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=nonlinear+dynamics+and+chaos&qid=1637418192&sr=8-1
bzw. seine entsprechende Reihe von Videos bei Youtube
https://www.youtube.com/playlist?list=PLbN57C5Zdl6j_qJA-pARJnKsmROzPnO9V
vorschlagen.

**Comment by Coarl93** [comment]
Danke für die Empfehlung,  mit der Videoreihe habe ich ja erstmal was zu tun. Buch ist bestellt :) 
Ich habe einen ersten versuch dazu mal in Python umgestetzt. Es sieht auf den ersten blick mal nicht schlecht aus, muss jedoch fällt mir noch eine genau Verifizierung der Ergebnisse schwer.

Viele Grüße
