### ISSUE TITLE
Feedback zu Überwachung Festplattenstatus mit Grafana

### ISSUE THREAD

**Issue by DrTron** [elbosso/elbosso.github.io#9]
[Überwachung Festplattenstatus mit Grafana](https://elbosso.github.io/ueberwachung_festplattenstatus_grafana)

Da ich auch gerade umsetzen wollte, den Status in Grafana sehen zu koennen, bin ich auf Deinen Post gestossen. Ich fragte mich allerdings, warum so kompliziert mit zwei Scripten und dem Schreiben des Status auf Platte?

Ich habe das mal in einem Script zusammengefasst, welches direkt einen telegraf-kompatiblen Output liefert. Also fuer jede Platte einmal den standby-status auslesen:

`sdastat=$(/sbin/hdparm -C /dev/sda|grep "drive state is"|cut -d ':' -f 2 |rev|cut -d ' ' -f 1|rev)
if [ "$sdastat" = "standby" ]; then
        sda=0
else
        sda=1
fi
`
Dann hat man den Status in der Variable "sd[a-z]", und kann dann einfach zusammenfuegen und nach stdout ausgeben:

`echo "home_diskstat,host=${HOST} sda=${sda}i,sdb=${sdb}i,.....,sdz=${sdz}i"`

Nur so eine Idee. Hat auch den Vorteil, dass nur eine Zeile pro Messung in der Datenbank auftaucht.

**Comment by DrTron** [comment]
Selbstverstaendlich ;-)

**Comment by DrTron** [comment]
Ich habe das nochmal aufgegriffen und etwas modifiziert, bedingt dadurch, dass sata-drives ihren Buchstaben nach der Initialisierung bekommen, und bei meiner Mainboard/Plattenkombination das nicht immer konsistent ist, d.h., sie wechseln ab und zu mal den Namen. Daher habe ich das script so geaendert, dass es /dev/disk/by-id abgrast, alles mitnimmt, was eine Platte (und keine Partition) ist, den Namen aus smartctl extrahiert (das braucht jq als dependency) und dann den Status schreibt. Funktioniert mit vier Platten bisher gut.

file:///home/tron/Documents/diskstat.txt

**Comment by elbosso** [comment]
done!
